### ISSUE TITLE
支持 Android Q READ_PHONE_STATE

### ISSUE THREAD

**Issue by jerryhu** [KF5/KF5SDK-Andriod2.0#11]
Android Q不再支持READ_PHONE_STATE权限

请更新代码

**Comment by ChosenKing** [comment]
Github已更新，麻烦重新集成一下，感谢配合！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jerryhu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 上午10:28
收件人:&nbsp;"KF5/KF5SDK-Andriod2.0"<KF5SDK-Andriod2.0@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[KF5/KF5SDK-Andriod2.0] 支持 Android Q READ_PHONE_STATE (#11)




Android Q不再支持READ_PHONE_STATE权限
 
请更新代码
