### ISSUE TITLE
isAnnotationPresent编译不通过

### ISSUE THREAD

**Issue by 2ndtonone** [KF5/KF5SDK-Andriod2.0#2]
Information:Gradle tasks [:app:assembleDebug]
F:\workspace2\KF5SDK-Andriod2.0-master\kf5sdk-master-v2\kf5sdkModule\src\main\java\com\kf5\sdk\system\permission\EasyPermissions.java
Error:(320, 23) 错误: 找不到符号
符号:   方法 isAnnotationPresent(Class<AfterPermissionGranted>)
位置: 类型为Method的变量 method
Error:Execution failed for task ':kf5sdkModule:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 16.7 secs
Information:2 errors
Information:0 warnings
Information:See complete output in console

编译不通过

**Comment by KF5** [comment]
jdk版本是多少？

**Comment by 2ndtonone** [comment]
1.8
![image](https://user-images.githubusercontent.com/10624864/28418294-c6ff0500-6d8d-11e7-89e2-814d42d4bebe.png)
